### ISSUE TITLE
Need a tutorial of flashing JDC AX1800 pro

### ISSUE THREAD

**Issue by permheaddamage** [breeze303/OpenWrt#12]
In JDC AX1800 pro's default EMMC layout, rootfs size is 60MB.
Here the compiled binary is more than 80MB. Please help put a tutorial of how to flash it to the device.
Or put a config of compiling a  rootfs less than 60MB.
Thanks~

**Comment by czghzh** [comment]
我不知道你的怎么才60M,也许你得从别的地方找到办法先修改你的EMMC布局，然后再来这里下载ROM,
![Screenshot_20240511_174051](https://github.com/breeze303/OpenWrt/assets/58479835/e90c0631-55d1-452a-b64b-61b8b02ebce6)
这是我的jdc ac1800

**Comment by permheaddamage** [comment]
原厂是60m的rootfs。。这是我没有改过分区表的gpt分区：
![image](https://github.com/breeze303/OpenWrt/assets/61133438/973cdbfb-f09e-4379-8f4e-04d20a1ec36e)
能不能出一个60m以下的默认配置给这个分区表用？其他的东西我可以自己装进overlay

**Comment by breeze303** [comment]
可以自行把docker去掉编译

**Comment by sundayfly** [comment]
刷了lean istore 这里固件升级不了 在uboot 更新也是故障 红灯 有刷机资源参考吗

**Comment by czghzh** [comment]
想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个: 
https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro

**Comment by sundayfly** [comment]
刷回原厂 再刷

> 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个: https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro

刷回原厂 再刷这个 05.02-JDC_AX1800-PRO-SQUASHFS-FACTORY.BIN  红灯故障中  不会是uboot的问题吧

**Comment by czghzh** [comment]
https://wwi.lanzoup.com/im2jc1gdai9i
密码：7owq
刷这个可能变大分区

**Comment by sundayfly** [comment]
> https://wwi.lanzoup.com/im2jc1gdai9i 密码：7owq 刷这个可能变大分区，试下uboot刷入，或命令 dd if=/tmp/tmp/kernel.bin of=/dev/mmcblk0p16 dd if=/tmp/tmp/rootfs.bin of=/dev/mmcblk0p18

<img width="594" alt="image" src="https://github.com/breeze303/OpenWrt/assets/14009345/a581220a-6edb-424d-bc5c-e976287fd03e">

试过在uboot 更新factory固件不行
scp kernel.bin rootfs.bin    dd写入mmcblk0p16和18 不行
用ubin 合并lean的上面两个文件是可以刷入
你链接的 kernel.bin rootfs.bin 用ubin 合并 刷入也不行

我再研究下大分区问题

**Comment by permheaddamage** [comment]
> 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个: https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro

我fork了一个，把各种翻墙和docker去掉了，编译出来只有30m不到，刷进去运行很正常

**Comment by 675658** [comment]
> > 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个: https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro
> 
> 我fork了一个，把各种翻墙和docker去掉了，编译出来只有30m不到，刷进去运行很正常

https://github.com/lgs2007m/Actions-OpenWrt/blob/main/%E5%88%B7%E6%9C%BA%E6%95%99%E7%A8%8B/%E4%BA%AC%E4%B8%9C%E4%BA%91AX1800-Pro%E4%BA%9A%E7%91%9F_AX6600%E9%9B%85%E5%85%B8%E5%A8%9C%E5%88%86%E5%8C%BA%E5%A4%87%E4%BB%BD%2BTTL%E5%8F%8C%E5%88%86%E5%8C%BA%E5%88%B7%E6%9C%BA%2B%E5%9B%9E%E5%8E%9F%E5%8E%82%2BUSB%E6%95%91%E7%A0%96%E6%95%99%E7%A8%8B20240510.md
这里有刷大分区的方法， 亲测可以使用

**Comment by permheaddamage** [comment]
> 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个: https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro

对了openwrt.ai版本的usb有问题，插3.0设备kernel log里都是high speed

**Comment by permheaddamage** [comment]
啊这里的6.6.30好像5ghz wifi有问题，显示连接速度1200mbps，实际吞吐才200多。
有线正常。

**Comment by sundayfly** [comment]
> 啊这里的6.6.30好像5ghz wifi有问题，显示连接速度1200mbps，实际吞吐才200多。 有线正常。

刚测试了下 5g wifi 确实不太稳定 很近很近 波动还是很大 连接速度可以跌到8Mbps

**Comment by czghzh** [comment]
5g我的发现你们的问题，你们是不是有去改大功率？用默认的就是最好的，我的1000M电信用5Gwifi ,下载跑到800多M

**Comment by czghzh** [comment]
![Screenshot_20240512_230210](https://github.com/breeze303/OpenWrt/assets/58479835/7020f6d1-f2c9-44de-8226-b79c60c3b2ee)
![Uploading Screenshot_20240512_230331.png…]()

**Comment by czghzh** [comment]
5g我没发现你们的问题，你们是不是有去改大功率？用默认的就是最好的，我的1000M电信用5Gwifi ,下载跑到800多M
![Screenshot_20240512_230331](https://github.com/breeze303/OpenWrt/assets/58479835/9d7e4619-a6f6-4794-9479-975414bad236)
![Screenshot_20240512_230210](https://github.com/breeze303/OpenWrt/assets/58479835/79713f63-732a-4cb2-a2aa-deeea51a77e7)

**Comment by alliwang** [comment]
> > > 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个: https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro
> > 
> > 
> > 我fork了一个，把各种翻墙和docker去掉了，编译出来只有30m不到，刷进去运行很正常
> 
> https://github.com/lgs2007m/Actions-OpenWrt/blob/main/%E5%88%B7%E6%9C%BA%E6%95%99%E7%A8%8B/%E4%BA%AC%E4%B8%9C%E4%BA%91AX1800-Pro%E4%BA%9A%E7%91%9F_AX6600%E9%9B%85%E5%85%B8%E5%A8%9C%E5%88%86%E5%8C%BA%E5%A4%87%E4%BB%BD%2BTTL%E5%8F%8C%E5%88%86%E5%8C%BA%E5%88%B7%E6%9C%BA%2B%E5%9B%9E%E5%8E%9F%E5%8E%82%2BUSB%E6%95%91%E7%A0%96%E6%95%99%E7%A8%8B20240510.md 这里有刷大分区的方法， 亲测可以使用

找不到他的Uboot，能分享下吗

**Comment by czghzh** [comment]
我用的是这个，你可以试下
https://mega.nz/file/o0IlVKrQ#1o6rsALEPZwlU16T5RckksfACCtrtmfKj9xVutu0JsU

**Comment by czghzh** [comment]
> > > 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个： https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro
> > 
> > 
> > 我fork了一个，把各种翻墙和docker去掉了，编译出来只有30m不到，刷进去运行很正常
> 
> https://github.com/lgs2007m/Actions-OpenWrt/blob/main/%E5%88%B7%E6%9C%BA%E6%95%99%E7%A8%8B/%E4%BA%AC%E4%B8%9C%E4%BA%91AX1800-Pro%E4%BA%9A%E7%91%9F_AX6600%E9%9B%85%E5%85%B8%E5%A8%9C%E5%88%86%E5%8C%BA%E5%A4%87%E4%BB%BD%2BTTL%E5%8F%8C%E5%88%86%E5%8C%BA%E5%88%B7%E6%9C%BA%2B%E5%9B%9E%E5%8E%9F%E5%8E%82%2BUSB%E6%95%91%E7%A0%96%E6%95%99%E7%A8%8B20240510.md 这里有刷大分区的方法， 亲测可以使用

这样做还不只有60M的分区大小，我的分区600M

![Uploading Screenshot_20240513_165248.png…]()

**Comment by kidxiang** [comment]
> 可以自行把docker去掉编译

请问怎么把docker去掉编译？

**Comment by 675658** [comment]
> 啊这里的6.6.30想要5ghz wifi有问题，显示连接速度1200mbps，实际吞吐才200多。 同步正常。

手动降低发射功率试试？
我降低到20db能跑到900多mbps，之前驱动自动27db只有300多mbps

**Comment by permheaddamage** [comment]
> > 啊这里的6.6.30想要5ghz wifi有问题，显示连接速度1200mbps，实际吞吐才200多。 同步正常。
> 
> 手动降低发射功率试试？ 我降低到20db能跑到900多mbps，之前驱动自动27db只有300多mbps

果然啊，我的ax210笔记本隔30cm测试，默认27db是200多mbps实际吞吐，改到20db就是700+mbps

**Comment by sundayhk** [comment]
> https://github.com/lgs2007m/Actions-OpenWrt/blob/main/%E5%88%B7%E6%9C%BA%E6%95%99%E7%A8%8B/%E4%BA%AC%E4%B8%9C%E4%BA%91AX1800-Pro%E4%BA%9A%E7%91%9F_AX6600%E9%9B%85%E5%85%B8%E5%A8%9C%E5%88%86%E5%8C%BA%E5%A4%87%E4%BB%BD%2BTTL%E5%8F%8C%E5%88%86%E5%8C%BA%E5%88%B7%E6%9C%BA%2B%E5%9B%9E%E5%8E%9F%E5%8E%82%2BUSB%E6%95%91%E7%A0%96%E6%95%99%E7%A8%8B20240510.md

我这测试20db 也是不太稳  还是qwrt无线稳些

**Comment by sundayhk** [comment]
> > > > 想要大分区不用自己去做分区，这与固件有关，我上次不知道刷了哪一个固件后就从60M变成600M了，也许你们在网上找找看，因为是刷了哪个固件我也忘了，要不你们试一下这个： https://openwrt.ai/?target=qualcommax%2Fipq60xx&id=jdc_ax1800-pro
> > > 
> > > 
> > > 我fork了一个，把各种翻墙和docker去掉了，编译出来只有30m不到，刷进去运行很正常
> > 
> > 
> > https://github.com/lgs2007m/Actions-OpenWrt/blob/main/%E5%88%B7%E6%9C%BA%E6%95%99%E7%A8%8B/%E4%BA%AC%E4%B8%9C%E4%BA%91AX1800-Pro%E4%BA%9A%E7%91%9F_AX6600%E9%9B%85%E5%85%B8%E5%A8%9C%E5%88%86%E5%8C%BA%E5%A4%87%E4%BB%BD%2BTTL%E5%8F%8C%E5%88%86%E5%8C%BA%E5%88%B7%E6%9C%BA%2B%E5%9B%9E%E5%8E%9F%E5%8E%82%2BUSB%E6%95%91%E7%A0%96%E6%95%99%E7%A8%8B20240510.md 这里有刷大分区的方法， 亲测可以使用
> 
> 这样做还不只有60M的分区大小，我的分区600M
> 
> ![Screenshot_20240513_165248](https://private-user-images.githubusercontent.com/58479835/329987719-5301ee95-510c-4a5b-a70e-f09cb71ba4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTk1NjUsIm5iZiI6MTcxNTY5OTI2NSwicGF0aCI6Ii81ODQ3OTgzNS8zMjk5ODc3MTktNTMwMWVlOTUtNTEwYy00YTViLWE3MGUtZjA5Y2I3MWJhNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE1MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YjVkZTYxYWU3ZGNjNDRlYWQxYmU5MjFmNzI3N2YzMDQ0ZGI4N2QyMjAxZmQwYmQ0MGM1YWM0NWViYjMzMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BgF4uvQfhDX22FzlGyjBvlR0psMM6NUFVg3-d5B75lQ)

刷这个大分区了 还有是很多固件刷不了 应该还是分区的问题

**Comment by permheaddamage** [comment]
我本来指望这个cpu更强可以把BT下载机的任务也做了，结果我太天真了。。
一样512m的内存，rax3000m的可用内存在250m左右，BT速度受限于CPU，只能搞到大概15MB
这个亚瑟的可用内存只有50m，BT一跑起来没一会儿就kernel error：oom了。
空有那么强的cpu，不改内存没办法用，以后再也不碰高通了
