### ISSUE TITLE
config里面增加passwall2和filebrowser时，编译出错。

### ISSUE THREAD

**Issue by youfun** [breeze303/OpenWrt#13]
在config（ipq60xx-wifi(emmc).config）里面增加以下两项，

CONFIG_PACKAGE_luci-app-passwall2=y
CONFIG_PACKAGE_luci-app-filebrowser=y

然后执行action ipq60xx-wifi(emmc)
在编译固件阶段出错。报错如下：
```shell

checking for mbedtls_cipher_setup in -lmbedcrypto... yes
configure: error: MBEDTLS_CIPHER_MODE_CFB required
make[3]: *** [Makefile:130: /home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-libev-3.3.5/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
checking whether mbedtls supports Cipher Feedback mode or not... make[3]: Leaving directory '/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/feeds/packages/net/shadowsocks-libev'
time: package/feeds/packages/shadowsocks-libev/compile#14.10#1.22#16.00
    ERROR: package/feeds/packages/shadowsocks-libev failed to build.
make[2]: *** [package/Makefile:129: package/feeds/packages/shadowsocks-libev/compile] Error 1
make[2]: Leaving directory '/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt'
make[1]: *** [package/Makefile:123: /home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt'
make: *** [/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/include/toplevel.mk:233: world] Error 2


```

**Comment by breeze303** [comment]
# CONFIG_PACKAGE_ shadowsocks-libev is not set

加这句去掉就好，一般不会用到这个

**Comment by youfun** [comment]
> # CONFIG_PACKAGE_ shadowsocks-libev is not set
> 加这句去掉就好，一般不会用到这个

去掉之后还是报错，估计有依赖关系
```shell
: error: MBEDTLS_CIPHER_MODE_CFB required
make[3]: *** [Makefile:130: /home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-libev-3.3.5/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
checking whether mbedtls supports Cipher Feedback mode or not... make[3]: Leaving directory '/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/feeds/packages/net/shadowsocks-libev'
time: package/feeds/packages/shadowsocks-libev/compile#14.06#1.40#16.13
    ERROR: package/feeds/packages/shadowsocks-libev failed to build.
make[2]: *** [package/Makefile:129: package/feeds/packages/shadowsocks-libev/compile] Error 1
make[2]: Leaving directory '/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt'
make[1]: *** [package/Makefile:123: /home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt'
make: *** [/home/runner/work/OpenWrtjdc/OpenWrtjdc/openwrt/include/toplevel.mk:233: world] Error 2
```

**Comment by youfun** [comment]
```shell
Run cd $OPENWRT_PATH

WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
#
# configuration written to .config
#
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
```

**Comment by youfun** [comment]
查了下，这个在base库
package: libpcre
Name:libpcreVersion:8.45-3Description:A Perl Compatible Regular Expression library\\ \\Installed size:79kBDependencies:[libc](https://openwrt.org/packages/pkgdata/libc)Categories:[libraries](https://openwrt.org/packages/index/libraries)Repositories:baseArchitectures:[aarch64_cortex-a53](https://openwrt.org/docs/techref/instructionset/aarch64_cortex-a53), [aarch64_cortex-a72](https://openwrt.org/docs/techref/instructionset/aarch64_cortex-a72), [aarch64_generic](https://openwrt.org/docs/techref/instructionset/aarch64_generic), [arc_archs](https://openwrt.org/docs/techref/instructionset/arc_archs), [arm_arm1176jzf-s_vfp](https://openwrt.org/docs/techref/instructionset/arm_arm1176jzf-s_vfp), [arm_arm926ej-s](https://openwrt.org/docs/techref/instructionset/arm_arm926ej-s), [arm_cortex-a15_neon-vfpv4](https://openwrt.org/docs/techref/instructionset/arm_cortex-a15_neon-vfpv4), [arm_cortex-a7](https://openwrt.org/docs/techref/instructionset/arm_cortex-a7), [arm_cortex-a7_neon-vfpv4](https://openwrt.org/docs/techref/instructionset/arm_cortex-a7_neon-vfpv4), [arm_cortex-a8_vfpv3](https://openwrt.org/docs/techref/instructionset/arm_cortex-a8_vfpv3), [arm_cortex-a9](https://openwrt.org/docs/techref/instructionset/arm_cortex-a9), [arm_cortex-a9_neon](https://openwrt.org/docs/techref/instructionset/arm_cortex-a9_neon), [arm_fa526](https://openwrt.org/docs/techref/instructionset/arm_fa526), [arm_mpcore](https://openwrt.org/docs/techref/instructionset/arm_mpcore), [arm_xscale](https://openwrt.org/docs/techref/instructionset/arm_xscale), [i386_pentium4](https://openwrt.org/docs/techref/instructionset/i386_pentium4), [mips_24kc](https://openwrt.org/docs/techref/instructionset/mips_24kc), [mips_mips32](https://openwrt.org/docs/techref/instructionset/mips_mips32), [mipsel_24kc](https://openwrt.org/docs/techref/instructionset/mipsel_24kc), [mipsel_24kc_24kf](https://openwrt.org/docs/techref/instructionset/mipsel_24kc_24kf), [mipsel_74kc](https://openwrt.org/docs/techref/instructionset/mipsel_74kc), [mipsel_mips32](https://openwrt.org/docs/techref/instructionset/mipsel_mips32), [powerpc_464fp](https://openwrt.org/docs/techref/instructionset/powerpc_464fp), [powerpc_8540](https://openwrt.org/docs/techref/instructionset/powerpc_8540), [x86_64](https://openwrt.org/docs/techref/instructionset/x86_64)OpenWrt release:OpenWrt-22.03.0File size:80kBLicense:BSD-3-ClauseMaintainer:Thomas HeilBug report:[Bug reports](https://bugs.openwrt.org/)Source code:[Sources](https://github.com/openwrt/openwrt/tree/openwrt-22.03/package/libs/pcre)

**Comment by breeze303** [comment]
那你可能需要本地编译调整下
