### ISSUE TITLE
默认feeds里的small源有问题,如果加入shadowsocksr-libev就无法编译成功

### ISSUE THREAD

**Issue by ysuolmai** [breeze303/OpenWrt#15]
如果加入ssr编译就会出错, 而且貌似加入其他helloworld的源也还是用这个small里的库,导致编译不通过.

checking whether to build static libraries... yes
checking for pcre-config... pcre-config
checking for pcre headers in ... not found
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR
make[3]: *** [Makefile:67: /home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocksr-libev-2.5.3/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt/feeds/small/shadowsocksr-libev'
time: package/feeds/small/shadowsocksr-libev/compile#25.45#1.74#28.81
    ERROR: package/feeds/small/shadowsocksr-libev failed to build.
make[2]: *** [package/Makefile:129: package/feeds/small/shadowsocksr-libev/compile] Error 1
make[2]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt'
make[1]: *** [package/Makefile:123: /home/runner/work/OpenWrt/OpenWrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt'
make: *** [/home/runner/work/OpenWrt/OpenWrt/openwrt/include/toplevel.mk:233: world] Error 2

**Comment by ysuolmai** [comment]
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
#
# No change to .config
#
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist

直接删掉feeds里的small, 还有上面这个警告, 估计还是不能编译成功

**Comment by ysuolmai** [comment]
编译好了. 改了下代码, 调用diy脚本,并且在diy脚本里删掉这个三方的feeds
sed -i "/kenzok8/d" "feeds.conf.default"
rm -rf package/feeds/small
rm -rf package/feeds/kenzo

加上hellowowrld源码
git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld

编译没有问题了,虽然有个那个freeswitch的警告,但是编译没有问题.

**Comment by fermii11** [comment]
我一开始也编译不上，看来不止我一个人报错

**Comment by linocz1** [comment]
我想集成 https://github.com/honwen/luci-app-shadowsocks-rust 和 https://github.com/honwen/openwrt-shadowsocks-rust，请问一下应该如何修改那个配置文件

**Comment by ysuolmai** [comment]
> 我想集成 https://github.com/honwen/luci-app-shadowsocks-rust 和 [https://github.com/honwen/openwrt-shadowsocks-rust，请问一下应该如何修改那个配置文件](https://github.com/honwen/openwrt-shadowsocks-rust%EF%BC%8C%E8%AF%B7%E9%97%AE%E4%B8%80%E4%B8%8B%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E9%82%A3%E4%B8%AA%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

你可以参考我的github,我主页那个openwrt. 不是什么牛逼的改造，只是基于大佬的脚本和源码，加了一些自己需要的插件。基本上就是在action文件（.github/workflows文件夹里）的load custom configuration部分最后加这三行
        chmod +x $DIY_SCRIPT
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/$DIY_SCRIPT

然后去修改diy-script.sh文件，可以把原来的内容除了第一行，以及最后两行，其他全删了，然后中间加你要的包，格式是
git clone 你要加的github源 package/包名

最后去修改下configs里的对应设备的config文件，加上你要的插件
CONFIG_PACKAGE_luci-app-rust=y
CONFIG_PACKAGE_openwrt-shadowsocks-rust=y
当然这步你可以和我一样直接用diy-script.sh直接去修改.config, echo挂在文件尾就行，这好处是尽量不修改大佬的源码，有啥更新的时候很方面合并。

这样就可以开始编译了。

**Comment by fermii11** [comment]
> > 我想集成 https://github.com/honwen/luci-app-shadowsocks-rust 和 [https://github.com/honwen/openwrt-shadowsocks-rust，请问一下应该如何修改那个配置文件](https://github.com/honwen/openwrt-shadowsocks-rust%EF%BC%8C%E8%AF%B7%E9%97%AE%E4%B8%80%E4%B8%8B%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E9%82%A3%E4%B8%AA%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
> 
> 你可以参考我的github，我主页那个openwrt.不是什么牛逼的改造，只是基于大佬的脚本和源码，加了一些自己需要的插件。基本上就是在action文件（.github/workflows文件夹里）的load custom configuration部分最后加这三行 chmod +x $DIY_SCRIPT cd $OPENWRT_PATH $GITHUB_WORKSPACE/$DIY_SCRIPT
> 
> 然后去修改 diy-script.sh 文件，可以把原来的内容除了第一行，以及最后两行，其他全删了，然后中间加你要的包，格式是 git clone 你要加的github源 package/包名
> 
> 最后去修改下configs里的对应设备的config文件，加上你要的插件 CONFIG_PACKAGE_luci-app-rust=y CONFIG_PACKAGE_openwrt-shadowsocks-rust=y 当然，这步你可以和我一样直接用 diy-script.sh 直接去修改.config， echo挂在文件尾就行，这好处是尽量不修改大佬的源码，有啥更新的时候很方面合并。
> 
> 这样就可以开始编译了。

漂亮的思路，我这就去实操

**Comment by linocz1** [comment]
> > 我想集成 https://github.com/honwen/luci-app-shadowsocks-rust 和 [https://github.com/honwen/openwrt-shadowsocks-rust，请问一下应该如何修改那个配置文件](https://github.com/honwen/openwrt-shadowsocks-rust%EF%BC%8C%E8%AF%B7%E9%97%AE%E4%B8%80%E4%B8%8B%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E9%82%A3%E4%B8%AA%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)
> 
> 你可以参考我的github，我主页那个openwrt.不是什么牛逼的改造，只是基于大佬的脚本和源码，加了一些自己需要的插件。基本上就是在action文件（.github/workflows文件夹里）的load custom configuration部分最后加这三行 chmod +x $DIY_SCRIPT cd $OPENWRT_PATH $GITHUB_WORKSPACE/$DIY_SCRIPT
> 
> 然后去修改 diy-script.sh 文件，可以把原来的内容除了第一行，以及最后两行，其他全删了，然后中间加你要的包，格式是 git clone 你要加的github源 package/包名
> 
> 最后去修改下configs里的对应设备的config文件，加上你要的插件 CONFIG_PACKAGE_luci-app-rust=y CONFIG_PACKAGE_openwrt-shadowsocks-rust=y 当然，这步你可以和我一样直接用 diy-script.sh 直接去修改.config， echo挂在文件尾就行，这好处是尽量不修改大佬的源码，有啥更新的时候很方面合并。
> 
> 这样就可以开始编译了。

好的，感谢
