### ISSUE TITLE
能做一个小于60M的JDC-AX1800Pro的固件吗？

### ISSUE THREAD

**Issue by kidxiang** [breeze303/OpenWrt#16]
自己试着编译了一个，但老是有问题，总是缺少组件，大佬能帮忙编译一个吗？不要docker、istore、晶晨宝盒等占用比较大的就行，谢谢啦

**Comment by czghzh** [comment]
https://github.com/czghzh/OpenWrt1/releases
能你编译了个没docker,小60M的

**Comment by kidxiang** [comment]
> https://github.com/czghzh/OpenWrt1/releases 给你编译了个没docker,小60M的

谢谢大佬

**Comment by yiesum** [comment]
> 刷写gpt，然后扩容root 分区，支持最大2G

请问具体证明操作呢？

**Comment by 9thChasingWindGirl** [comment]
> https://github.com/czghzh/OpenWrt1/releases 给你编译了个没docker,小60M的

fw4?upnp没公网能用吗

**Comment by lgs2007m** [comment]
> > 刷写gpt，然后扩容root 分区，支持最大2G
> 
> 请问具体证明操作呢？

看我的教程，双分区gpt有512MB、1024MB、2048MB三种，支持原厂系统，我改的uboot支持大于100MB的固件
https://github.com/lgs2007m/Actions-OpenWrt/tree/main/刷机教程

**Comment by xiongyumail** [comment]
改分区表把 rootfs 和 rootfs_1 改为 512M (注意备份原始分区)， 最后把备份的几个分区再刷进去。
[mmcblk0_GPT.zip](https://github.com/breeze303/OpenWrt/files/15411331/mmcblk0_GPT.zip)

**Comment by kidxiang** [comment]
> > > 刷写gpt，然后扩容root 分区，支持最大2G
> > 
> > 
> > 请问具体证明操作呢？
> 
> 看我的教程，双分区gpt有512MB、1024MB、2048MB三种，支持原厂系统，我改的uboot支持大于100MB的固件 [https://github.com/lgs2007m/Actions-OpenWrt/tree/main/刷机教程](https://github.com/lgs2007m/Actions-OpenWrt/tree/main/%E5%88%B7%E6%9C%BA%E6%95%99%E7%A8%8B)

谢谢大佬，已改1024MB分区，好用！

**Comment by kidxiang** [comment]
> 改分区表把 rootfs 和 rootfs_1 改为 512M (注意备份原始分区)， 最后把备份的几个分区再刷进去。 [mmcblk0_GPT.zip](https://github.com/breeze303/OpenWrt/files/15411331/mmcblk0_GPT.zip)

谢谢大佬指点
