### ISSUE TITLE
IPQ8000的编译不了

### ISSUE THREAD

**Issue by ysuolmai** [breeze303/OpenWrt#8]
大佬,ipq8000的编译失败,貌似你的action也是, 错误码我贴一下,应该是一样的

`*
  * LED driver for blink(1) USB RGB LED is under Special HID drivers (HID_THINGM)
  *
  LED support for the BlinkM I2C RGB LED (LEDS_BLINKM) [N/m/y/?] n
  LED support for LEDs on system controllers (LEDS_SYSCON) [N/y/?] n
  LED support for the Mellanox switches management control (LEDS_MLXREG) [N/m/y/?] n
  Userspace LED support (LEDS_USER) [N/m/y/?] n
  LED support for SPI LED controller with a single byte (LEDS_SPI_BYTE) [N/m/y/?] n
  LED driver for LM3697 (LEDS_LM3697) [N/m/y/?] n
  *
  * Flash and Torch LED drivers
  *
  *
  * RGB LED drivers
  *
  LEDs group multi-color support (LEDS_GROUP_MULTICOLOR) [N/m/y/?] n
  PWM driven multi-color LED Support (LEDS_PWM_MULTICOLOR) [N/m/y/?] n
make[7]: *** [Makefile:697: syncconfig] Error 2
/home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.28/Makefile:775: include/config/auto.conf.cmd: No such file or directory
make[6]: *** [/home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.28/Makefile:798: include/config/auto.conf.cmd] Error 2
make[5]: *** [Makefile:234: __sub-make] Error 2
make[4]: *** [Makefile:23: /home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.28/.modules] Error 2
make[3]: *** [Makefile:11: compile] Error 2
make[2]: *** [target/Makefile:32: target/linux/compile] Error 1
  LED support for Qualcomm LPG (LEDS_QCOM_LPG) [N/m/y/?] (NEW) make[5]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.28'
make[4]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt/target/linux/qualcommax'
make[3]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt/target/linux'
time: target/linux/compile#1.32#0.50#1.78
    ERROR: target/linux failed to build.
make[2]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt'
make[1]: *** [target/Makefile:25: /home/runner/work/OpenWrt/OpenWrt/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/runner/work/OpenWrt/OpenWrt/openwrt'
make: *** [/home/runner/work/OpenWrt/OpenWrt/openwrt/include/toplevel.mk:233: world] Error 2
Error: Process completed with exit code 2.`

**Comment by breeze303** [comment]
修复了
